#!/usr/bin/env bash
set -euo pipefail

# Deploy a prebuilt frontend artifact (.zip) to a release directory and switch symlink.
#
# Example:
#   bash scripts/deploy-frontend.sh \
#     --artifact /data/releases/sqtoimage-frontend-20260415_143433.zip \
#     --app-root /var/www/sqtoimage-frontend \
#     --reload-nginx

ARTIFACT=""
APP_ROOT="/var/www/sqtoimage-frontend"
RELEASE_TAG=""
CURRENT_LINK=""
RELOAD_NGINX="false"

usage() {
  cat <<'EOF'
Usage:
  deploy-frontend.sh --artifact <zip-path> [options]

Required:
  --artifact <path>        Frontend zip artifact generated by scripts/pack-frontend.ps1

Optional:
  --app-root <path>        Base directory for frontend deploy (default: /var/www/sqtoimage-frontend)
  --release-tag <tag>      Release tag (default: parsed from artifact name or timestamp)
  --current-link <path>    Symlink path (default: <app-root>/current)
  --reload-nginx           Run nginx -t && systemctl reload nginx after switching symlink
  -h, --help               Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --artifact)
      ARTIFACT="${2:-}"
      shift 2
      ;;
    --app-root)
      APP_ROOT="${2:-}"
      shift 2
      ;;
    --release-tag)
      RELEASE_TAG="${2:-}"
      shift 2
      ;;
    --current-link)
      CURRENT_LINK="${2:-}"
      shift 2
      ;;
    --reload-nginx)
      RELOAD_NGINX="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${ARTIFACT}" ]]; then
  echo "ERROR: --artifact is required." >&2
  usage
  exit 1
fi

if [[ ! -f "${ARTIFACT}" ]]; then
  echo "ERROR: artifact not found: ${ARTIFACT}" >&2
  exit 1
fi

if [[ "${ARTIFACT}" != *.zip ]]; then
  echo "ERROR: artifact must be a .zip file." >&2
  exit 1
fi

if ! command -v unzip >/dev/null 2>&1; then
  echo "ERROR: unzip is required." >&2
  exit 1
fi

if [[ -z "${RELEASE_TAG}" ]]; then
  base_name="$(basename "${ARTIFACT}")"
  if [[ "${base_name}" =~ sqtoimage-frontend-(.+)\.zip$ ]]; then
    RELEASE_TAG="${BASH_REMATCH[1]}"
  else
    RELEASE_TAG="$(date +%Y%m%d_%H%M%S)"
  fi
fi

if [[ -z "${CURRENT_LINK}" ]]; then
  CURRENT_LINK="${APP_ROOT}/current"
fi

RELEASE_DIR="${APP_ROOT}/releases/${RELEASE_TAG}"
TMP_DIR="${RELEASE_DIR}.tmp"

echo "Deploying frontend artifact..."
echo "  artifact:     ${ARTIFACT}"
echo "  app_root:     ${APP_ROOT}"
echo "  release_tag:  ${RELEASE_TAG}"
echo "  release_dir:  ${RELEASE_DIR}"
echo "  current_link: ${CURRENT_LINK}"

mkdir -p "${APP_ROOT}/releases"
rm -rf "${TMP_DIR}"
mkdir -p "${TMP_DIR}"

unzip -q "${ARTIFACT}" -d "${TMP_DIR}"

if [[ ! -f "${TMP_DIR}/index.html" ]]; then
  echo "ERROR: invalid artifact, index.html not found at zip root." >&2
  rm -rf "${TMP_DIR}"
  exit 1
fi

if [[ -d "${RELEASE_DIR}" ]]; then
  echo "WARNING: release dir already exists, replacing: ${RELEASE_DIR}"
  rm -rf "${RELEASE_DIR}"
fi

mv "${TMP_DIR}" "${RELEASE_DIR}"
ln -sfn "${RELEASE_DIR}" "${CURRENT_LINK}"

echo "Symlink switched:"
echo "  ${CURRENT_LINK} -> ${RELEASE_DIR}"

if [[ "${RELOAD_NGINX}" == "true" ]]; then
  if ! command -v nginx >/dev/null 2>&1; then
    echo "ERROR: nginx command not found." >&2
    exit 1
  fi
  nginx -t
  systemctl reload nginx
  echo "Nginx config test passed and reloaded."
fi

echo "Frontend deploy completed."

